# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Aspose.Cells for Go via C++ build and test on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Build Aspose.Cells for Go via C++
      env:
          PATH: ${{ github.workspace }}/lib/win_x86_64;${env:PATH}        
      run: |
        dir "${{ github.workspace }}/"
        echo "PATH: ${env:PATH}"
        go build -v ./...

    - name: Run Example Code.
      env:
          PATH: ${{ github.workspace }}/lib/win_x86_64;${env:PATH}      
      run: |
        cd samples        
        go run .
