# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Aspose.Cells for Go via C++ build and test on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Run Example Code
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set CGO_ENABLED=1
        set CC=cl.exe
        set CXX=cl.exe
        set PATH=%CD%\lib\win_x86_64;%PATH%
        set CGO_CFLAGS=
        set CGO_CXXFLAGS=
        echo "Current dir: $(pwd)"
        dir "${{ github.workspace }}/lib/win_x86_64"
        cd samples
        go run .
      shell: cmd
