# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Aspose.Cells for Go via C++ build and test on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Run Example Code
      env:
        CGO_ENABLED: 1    
        CC: cl.exe
        CXX: cl.exe
        PATH: ${{ github.workspace }}/lib/win_x86_64;${env:PATH}
      run: |
        echo "Current dir: $(Get-Location)"
        dir "${{ github.workspace }}/lib/win_x86_64"
        cd samples
        go run .
      shell: powershell
